[project]
name = "bronya"
version = "0.1.0"
description = "Civilization monitor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "argon2-cffi>=23.1.0",
    "fastapi[standard]>=0.115.12",
    "pydantic>=2.11.3",
    "surrealdb>=1.0.3",
]
