name: Lints

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  lint:
    name: Code Lint (Frontend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install

      - name: Lint (Biome)
        run: pnpm biome ci

  lint-backend:
    name: Code Lint (Backend)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install
      - name: Setup ruff
        run: uv tool install ruff
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Lint
        run: ruff check .
      - name: Format
        run: ruff format --diff .

  code-spell:
    name: Spell Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Code Spell Check
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**"
          config: .cspell.json
          strict: true
          verbose: true
